### ISSUE TITLE
Remove <b> tag from the following tags:

### ISSUE THREAD

**Issue by Ancsur2002** [TTSBand/-Rewriting-Task-2-of-test-project#2]
**- title tag
- h1 tag
- h2 tag**

**Comment by Ancsur2002** [comment]
Reason: The stylesheet will do the formatting, this is why we are using tag editors in the first place ;)

**Comment by LergoVion** [comment]
- title: CHECK 
- h1 : CHECK 
- h2: CHECK

**Comment by Ancsur2002** [comment]
Done
